name: Build binaries

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install Python packages
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt

      - name: Build for Windows
        run: |
          pyinstaller --onefile --noconsole --name LitScholar --icon icon.ico gui.py
          mv dist/LitScholar.exe LitScholar.exe

      - name: Build for Linux
        run: |
          pyinstaller --onefile --noconsole --name LitScholar-Linux --icon icon.ico gui.py
          mv dist/LitScholar-Linux LitScholar-Linux

      - name: Build for macOS
        run: |
          pyinstaller --onefile --noconsole --name LitScholar-Mac --icon icon.ico gui.py
          mv dist/LitScholar-Mac LitScholar-Mac

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: LitScholar-binaries
          path: |
            LitScholar.exe
            LitScholar-Linux
            LitScholar-Mac
