name: Build binaries

on:
  push:
  pull_request:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install Python packages
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt

      - name: Build for Windows
        run: |
          pyinstaller --onefile --noconsole --name LitScholar --icon icon.ico gui.py

      - name: Build for Linux
        run: |
          pyinstaller --onefile --noconsole --name LitScholar-Linux --icon icon.ico gui.py

      - name: Build for macOS
        run: |
          pyinstaller --onefile --noconsole --name LitScholar-Mac --icon icon.ico gui.py

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: LitScholar-binaries
          path: |
            dist/LitScholar.exe
            dist/LitScholar-Linux
            dist/LitScholar-Mac


      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/LitScholar.exe
          asset_name: LitScholar.exe
          asset_content_type: application/octet-stream

      - name: Upload release asset
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/LitScholar-Linux
          asset_name: LitScholar-Linux
          asset_content_type: application/octet-stream

      - name: Upload release asset
        id: upload-release-asset-3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/LitScholar-Mac
          asset_name: LitScholar-Mac
          asset_content_type: application/octet-stream